### ISSUE TITLE
mapping "bridge"

### ISSUE THREAD

**Issue by Blqtent** [Steve987321/toadclient#2]
Maybe classloader or mapping issue?
Or injection issue.

**Comment by Blqtent** [comment]
Hook issue with swapbuffers

**Comment by Steve987321** [comment]
Hello, sorry for late response, but did you found the solution to your problem? @Blqtent

**Comment by Blqtent** [comment]
yes but I have a question
In the mappings, what does "bridge" mean?
Like bridge$getTheWorld

**Comment by Blqtent** [comment]
wait so where did u get the mappings from tho? I thought lunar's mappings were just the normal unobfuscated names

**Comment by Steve987321** [comment]
The classes are unobfuscated, so I simply ran the jvm functions on these classes to get their properties. 
The function that logs them is [loop_through_class](https://github.com/Steve987321/toadclient/blob/ad302ce99c39ca4e7e67da5673756b94e28d2fd0/ToadClient/Toad/MC/utils/mcutils.cpp#L268)

**Comment by Blqtent** [comment]
bruh it crashes so much bc it cant get mappings.
Its so random, like sometimes it can get them next time it cant

**Comment by Steve987321** [comment]
Make sure you do any additional checks before you call the function, sometimes classes could also be obfuscated. If you also want to get the fields you could uncomment the jvmti code in the init stage of the client.
