### ISSUE TITLE
Crash when in a world

### ISSUE THREAD

**Issue by scarifyFX** [Steve987321/toadclient#4]
Lunar Client both 1.8.9 and 1.7.10 crashes when I join a world
[2bb7815a-d22c-4733-b656-96eabbf06d26-master.log](https://github.com/user-attachments/files/16247762/2bb7815a-d22c-4733-b656-96eabbf06d26-master.log)

**Comment by scarifyFX** [comment]
[Toad.log](https://github.com/user-attachments/files/16247933/Toad.log)
I even compiled it myself and tried

**Comment by Steve987321** [comment]
Hello, Thanks for creating an issue and sending the log files

I've tested this too and see the issue (the mapping name has been updated), I will push a commit in a few minutes with this fixed and some other WIP stuff.

**Comment by Steve987321** [comment]
This should be fixed, could you recompile and try again and see if it still crashes?

**Comment by scarifyFX** [comment]
I went outside for a walk however I will test the new update soon when I get home.

**Comment by Steve987321** [comment]
Haha alright enjoy your walk man 👍

**Comment by scarifyFX** [comment]
https://github.com/user-attachments/assets/c12a95d1-2403-42d0-b7fe-8eb67519a703
