### ISSUE TITLE
still crashes when attaching

### ISSUE THREAD

**Issue by shaff1337** [Steve987321/toadclient#5]
i click lunar client in the loader and it crashes instantly after the "fix"

also make it work on feather client

**Comment by strea404** [comment]
plz fix crashing on latest lunar ver

**Comment by Steve987321** [comment]
> i click lunar client in the loader and it crashes instantly after the "fix"
> 
> also make it work on feather client

Sorry that one was fixing a crash when in world #4 

> plz fix crashing on latest lunar ver

I don't know what causes the crash on inject as I also can't replicate this issue with the newest version. Some people have this crash and some people don't for some reason

**Comment by l1nxxwrld** [comment]
it crashes on both 1.8.9. and 1.7.10

**Comment by shaff1337** [comment]
> > i click lunar client in the loader and it crashes instantly after the "fix"
> > also make it work on feather client
> 
> Sorry that one was fixing a crash when in world #4
> 
> > plz fix crashing on latest lunar ver
> 
> I don't know what causes the crash on inject as I also can't replicate this issue with the newest version. Some people have this crash and some people don't for some reason

error happens for me on 1.8.9 since thats what i mainly use. also including feather client support would be great if u could add support for it. appc it

**Comment by Steve987321** [comment]
I pushed something that might fix the crash on inject. I am not sure as I couldn't test it. 

> > > i click lunar client in the loader and it crashes instantly after the "fix"
> > > also make it work on feather client
> > 
> > 
> > Sorry that one was fixing a crash when in world #4
> > > plz fix crashing on latest lunar ver
> > 
> > 
> > I don't know what causes the crash on inject as I also can't replicate this issue with the newest version. Some people have this crash and some people don't for some reason
> 
> error happens for me on 1.8.9 since thats what i mainly use. also including feather client support would be great if u could add support for it. appc it

I was working on the mapping generator that tries to find mappings based on hardcoded mappings information. So that you can try to inject into other clients.

**Comment by strea404** [comment]
[Toad.log](https://github.com/user-attachments/files/16333868/Toad.log)


> @strea404 Good to know its working now. Could you send the Toad.log file in your Documents folder?

**Comment by Steve987321** [comment]
Looks normal, try messing around with the settings. 

Here is a config you could try, maybe its your config.

```
{
   "aa_always_aim":false,
   "aa_bb":false,
   "aa_distance":5.388999938964844,
   "aa_enabled":true,
   "aa_fov":168,
   "aa_horizontal_only":false,
   "aa_invisibles":false,
   "aa_lockaim":false,
   "aa_mode":2,
   "aa_multipoint":true,
   "aa_speed":115.0,
   "ba_block_check":1,
   "ba_enabled":false,
   "ba_pitch_check":60.50600051879883,
   "ba_sneak":true,
   "bl_enabled":false,
   "bl_key":0,
   "bl_limit_seconds":5.0,
   "bl_show_trail":false,
   "bl_stop_incoming_packets":false,
   "block_esp_array":{
      
   },
   "blockesp_enabled":false,
   "cs_delay":47,
   "cs_enabled":false,
   "cs_items":[
      "Egg",
      "Snow",
      "Plank",
      "Stone",
      "Legging",
      "Boots",
      "Helmet",
      "Chestplate"
   ],
   "cs_key":4,
   "cs_show_slot_pos":false,
   "cs_slot_info":[
      {
         "beginx":-135,
         "beginy":-70,
         "resx":-1,
         "resy":-1,
         "spacex":35,
         "spacey":35
      },
      {
         "beginx":-154,
         "beginy":-112,
         "resx":1920,
         "resy":1080,
         "spacex":36,
         "spacey":35
      }
   ],
   "esp_bg":false,
   "esp_bgcola":0.44999998807907104,
   "esp_bgcolb":0.10000000149011612,
   "esp_bgcolg":0.10000000149011612,
   "esp_bgcolr":0.10000000149011612,
   "esp_border":false,
   "esp_enabled":true,
   "esp_fillcola":0.14509804546833038,
   "esp_fillcolb":1.0,
   "esp_fillcolg":1.0,
   "esp_fillcolr":1.0,
   "esp_fontsize":13.0,
   "esp_linecola":1.0,
   "esp_linecolb":0.0,
   "esp_linecolg":0.0,
   "esp_linecolr":1.0,
   "esp_mode":0,
   "esp_show_distance":false,
   "esp_show_health":false,
   "esp_show_name":false,
   "esp_show_sneak":false,
   "esp_static_width":0,
   "esp_text_cola":1.0,
   "esp_text_colb":1.0,
   "esp_text_colg":1.0,
   "esp_text_colr":1.0,
   "esp_text_shadow":false,
   "lc_bbStart":60,
   "lc_bbStop":60,
   "lc_blockhit":false,
   "lc_blockhitms":50,
   "lc_blockhitpause":false,
   "lc_breakblocks":false,
   "lc_check":1,
   "lc_enabled":true,
   "lc_maxcps":20,
   "lc_mincps":14,
   "lc_randb":{
      "0":{
         "dur":50,
         "fqmax":150,
         "fqmin":100,
         "n":1.2000000476837158,
         "tdur":3
      },
      "1":{
         "dur":80,
         "fqmax":150,
         "fqmin":100,
         "n":0.5,
         "tdur":5
      },
      "2":{
         "dur":100,
         "fqmax":200,
         "fqmin":150,
         "n":0.4000000059604645,
         "tdur":5
      },
      "3":{
         "dur":120,
         "fqmax":200,
         "fqmin":150,
         "n":1.0,
         "tdur":5
      },
      "4":{
         "dur":190,
         "fqmax":200,
         "fqmin":150,
         "n":-1.0,
         "tdur":5
      },
      "5":{
         "dur":50,
         "fqmax":200,
         "fqmin":100,
         "n":-1.5,
         "tdur":3
      }
   },
   "lc_randi":{
      "0":{
         "c":70,
         "f":35,
         "nmax":40.0,
         "nmin":10.0
      },
      "1":{
         "c":60,
         "f":50,
         "nmax":40.0,
         "nmin":20.0
      },
      "2":{
         "c":50,
         "f":150,
         "nmax":60.0,
         "nmin":40.0
      },
      "3":{
         "c":50,
         "f":40,
         "nmax":0.0,
         "nmin":-10.0
      }
   },
   "lc_randi2":{
      "0":{
         "c":70,
         "f":50,
         "nmax":50.0,
         "nmin":30.0
      },
      "1":{
         "c":50,
         "f":100,
         "nmax":80.0,
         "nmin":60.0
      },
      "2":{
         "c":60,
         "f":50,
         "nmax":0.0,
         "nmin":-10.0
      },
      "3":{
         "c":40,
         "f":60,
         "nmax":0.0,
         "nmin":-15.0
      }
   },
   "lc_smartcps":true,
   "lc_tradeassist":false,
   "lc_weaponsonly":false,
   "ncd_enabled":true,
   "rc_blocksonly":false,
   "rc_check":0,
   "rc_cps":12,
   "rc_enabled":true,
   "rc_startdelay":37,
   "ui_internal":false,
   "ui_list":false,
   "ui_mark":false,
   "vel_chance":100,
   "vel_delay":0,
   "vel_enabled":true,
   "vel_horizontal":100.0,
   "vel_jumpchance":40,
   "vel_jumpreset":true,
   "vel_kite":true,
   "vel_onlyclicking":true,
   "vel_onlymoving":true,
   "vel_vertical":100.0
}
```

**Comment by strea404** [comment]
> Looks normal, try messing around with the settings. Could also be something else that is blocking the client from moving ur mouse.
> 
> Here is a config you could try, maybe its your config.
> 
> ```
> {
>    "aa_always_aim":false,
>    "aa_bb":false,
>    "aa_distance":5.388999938964844,
>    "aa_enabled":true,
>    "aa_fov":168,
>    "aa_horizontal_only":false,
>    "aa_invisibles":false,
>    "aa_lockaim":false,
>    "aa_mode":2,
>    "aa_multipoint":true,
>    "aa_speed":115.0,
>    "ba_block_check":1,
>    "ba_enabled":false,
>    "ba_pitch_check":60.50600051879883,
>    "ba_sneak":true,
>    "bl_enabled":false,
>    "bl_key":0,
>    "bl_limit_seconds":5.0,
>    "bl_show_trail":false,
>    "bl_stop_incoming_packets":false,
>    "block_esp_array":{
>       
>    },
>    "blockesp_enabled":false,
>    "cs_delay":47,
>    "cs_enabled":false,
>    "cs_items":[
>       "Egg",
>       "Snow",
>       "Plank",
>       "Stone",
>       "Legging",
>       "Boots",
>       "Helmet",
>       "Chestplate"
>    ],
>    "cs_key":4,
>    "cs_show_slot_pos":false,
>    "cs_slot_info":[
>       {
>          "beginx":-135,
>          "beginy":-70,
>          "resx":-1,
>          "resy":-1,
>          "spacex":35,
>          "spacey":35
>       },
>       {
>          "beginx":-154,
>          "beginy":-112,
>          "resx":1920,
>          "resy":1080,
>          "spacex":36,
>          "spacey":35
>       }
>    ],
>    "esp_bg":false,
>    "esp_bgcola":0.44999998807907104,
>    "esp_bgcolb":0.10000000149011612,
>    "esp_bgcolg":0.10000000149011612,
>    "esp_bgcolr":0.10000000149011612,
>    "esp_border":false,
>    "esp_enabled":true,
>    "esp_fillcola":0.14509804546833038,
>    "esp_fillcolb":1.0,
>    "esp_fillcolg":1.0,
>    "esp_fillcolr":1.0,
>    "esp_fontsize":13.0,
>    "esp_linecola":1.0,
>    "esp_linecolb":0.0,
>    "esp_linecolg":0.0,
>    "esp_linecolr":1.0,
>    "esp_mode":0,
>    "esp_show_distance":false,
>    "esp_show_health":false,
>    "esp_show_name":false,
>    "esp_show_sneak":false,
>    "esp_static_width":0,
>    "esp_text_cola":1.0,
>    "esp_text_colb":1.0,
>    "esp_text_colg":1.0,
>    "esp_text_colr":1.0,
>    "esp_text_shadow":false,
>    "lc_bbStart":60,
>    "lc_bbStop":60,
>    "lc_blockhit":false,
>    "lc_blockhitms":50,
>    "lc_blockhitpause":false,
>    "lc_breakblocks":false,
>    "lc_check":1,
>    "lc_enabled":true,
>    "lc_maxcps":20,
>    "lc_mincps":14,
>    "lc_randb":{
>       "0":{
>          "dur":50,
>          "fqmax":150,
>          "fqmin":100,
>          "n":1.2000000476837158,
>          "tdur":3
>       },
>       "1":{
>          "dur":80,
>          "fqmax":150,
>          "fqmin":100,
>          "n":0.5,
>          "tdur":5
>       },
>       "2":{
>          "dur":100,
>          "fqmax":200,
>          "fqmin":150,
>          "n":0.4000000059604645,
>          "tdur":5
>       },
>       "3":{
>          "dur":120,
>          "fqmax":200,
>          "fqmin":150,
>          "n":1.0,
>          "tdur":5
>       },
>       "4":{
>          "dur":190,
>          "fqmax":200,
>          "fqmin":150,
>          "n":-1.0,
>          "tdur":5
>       },
>       "5":{
>          "dur":50,
>          "fqmax":200,
>          "fqmin":100,
>          "n":-1.5,
>          "tdur":3
>       }
>    },
>    "lc_randi":{
>       "0":{
>          "c":70,
>          "f":35,
>          "nmax":40.0,
>          "nmin":10.0
>       },
>       "1":{
>          "c":60,
>          "f":50,
>          "nmax":40.0,
>          "nmin":20.0
>       },
>       "2":{
>          "c":50,
>          "f":150,
>          "nmax":60.0,
>          "nmin":40.0
>       },
>       "3":{
>          "c":50,
>          "f":40,
>          "nmax":0.0,
>          "nmin":-10.0
>       }
>    },
>    "lc_randi2":{
>       "0":{
>          "c":70,
>          "f":50,
>          "nmax":50.0,
>          "nmin":30.0
>       },
>       "1":{
>          "c":50,
>          "f":100,
>          "nmax":80.0,
>          "nmin":60.0
>       },
>       "2":{
>          "c":60,
>          "f":50,
>          "nmax":0.0,
>          "nmin":-10.0
>       },
>       "3":{
>          "c":40,
>          "f":60,
>          "nmax":0.0,
>          "nmin":-15.0
>       }
>    },
>    "lc_smartcps":true,
>    "lc_tradeassist":false,
>    "lc_weaponsonly":false,
>    "ncd_enabled":true,
>    "rc_blocksonly":false,
>    "rc_check":0,
>    "rc_cps":12,
>    "rc_enabled":true,
>    "rc_startdelay":37,
>    "ui_internal":false,
>    "ui_list":false,
>    "ui_mark":false,
>    "vel_chance":100,
>    "vel_delay":0,
>    "vel_enabled":true,
>    "vel_horizontal":100.0,
>    "vel_jumpchance":40,
>    "vel_jumpreset":true,
>    "vel_kite":true,
>    "vel_onlyclicking":true,
>    "vel_onlymoving":true,
>    "vel_vertical":100.0
> }
> ```

i found the culprit, it was the "Raw Mouse Input" setting in lunar. Everything is working perfectly now. goated client fr

**Comment by Steve987321** [comment]
Oh nice that you found it, I'll see if I can fix that and thanks man
