### ISSUE TITLE
Fatal Error C1083

### ISSUE THREAD

**Issue by WayBackToHeaven** [Steve987321/toadclient#6]
Sorry if im being dumb, it's my first time using visual code 2022, never used it and i dont have any experience in programming, I just wanted to download your hack, and there isn't any releases you know what i mean? And this error is happening, what is it??w
![Captura de tela 2024-07-30 201024](https://github.com/user-attachments/assets/bc2919cf-13c0-4a89-8f99-c122eebaf232)

**Comment by WayBackToHeaven** [comment]
omg, after some really really long hours, i finally manage to do it, dude im so fucking tired, why dont you just give us the code already?

**Comment by Steve987321** [comment]
Sorry to hear that man, but this client isn't finished at the moment so I will be creating a release once there is a stable version of it.
